package enums;

public enum Actions {
    WORK, EARN, APPEARED, ENOUGH, WALK, SEE, COME, APPEAR, SIT, SITS, TALK, ASK, ANSWER, BOUGHT, DRAGGED,COMES
    //,WRITTEN,ENTERED,APPEAR,SITTING,TALKING,ASKED,EMPLOY,SAID,OPENED,DRAGGED,SIT,ENTEREDS,SITS


}
